[package]
name = "github-oauth-userinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
log = "0.4.21"
reqwest = { version = "0.12.4", features = ["json"] }
serde = "1.0.202"
serde_json = "1.0.117"
simple_logger = "5.0.0"
